# docker-compose.yml
redis:
  image: redis
  container_name: cache
  expose:
    - 6379

app:
  image: node:10
  volumes:
    - ./backend:/app
  working_dir: /app
  ports:
    - 3000:3000
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=3000
  command:
    sh -c 'yarn install && yarn dev'
  links:
    - redis